### ISSUE TITLE
Missing MAE module？

### ISSUE THREAD

**Issue by JimOriginal** [sx-zhang/SGM#1]
Thank you for the excellent work. However, I couldn't find the part about MAE in the code, and _sgm/model.py_ looks exactly like PONI. Is there some code that hasn't been shared yet?

**Comment by Sorrowa** [comment]
The "models_sgm_cross.py" would be the MAE, maybe. But I still cant find the LLM part ("..roberta/roberta_gibson_glm/{}.pt".format(d_gibson[i])). 

It looks more like an enhancement of an NLP model.
